"       _               
"   _ _|_|_____ ___ ___ 
"  | | | |     |  _|  _|
"   \_/|_|_|_|_|_| |___|
"                     

" Basic
syntax enable
set number
set numberwidth=1
set relativenumber
set mouse=a
set encoding=UTF-8
set ruler
set sw=2
so ~/.config/vim/plugins.vim
so ~/.config/vim/keys.vim
so ~/.config/vim/plugins-conf.vim

" Colors and theme
colorscheme one
set background=dark

" Setting true colors from terminal
if (has("termguicolors"))
  set termguicolors
endif 
